### ISSUE TITLE
project seems broken

### ISSUE THREAD

**Issue by ashayk** [mbientlab-projects/iOSSensorFusion#1]
Hi,

I'd love to give the sensor fusion project a go, but it seems broken. There is no SensorFusion target. The pod file target is wrong, etc, etc... Could you please fix the project? Thanks.

**Comment by sschiffli** [comment]
Just fixed it up!

**Comment by ashayk** [comment]
Thanks. Still many errors. Pod install says:
"[!] Unable to satisfy the following requirements:

- `Metawear-iOSAPI` required by `Podfile`
- `Metawear-iOSAPI (= 2.5.0)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `Metawear-iOSAPI, Metawear-iOSAPI (= 2.5.0)`."

Also, linking errors to FastCoding, MBProgressHud, etc...

**Comment by sschiffli** [comment]
Can you confirm you are opening SensorFusion.xcworkspace and not SensorFusion.xcodeproj?
Also, are you building for a iOS device and not a Simulator target?

Note that we do check in the Pods directory, so you don't have to run any pod commands before running too.
